awakesecurity/nixpkgs

nixos/modules/services/logging/logstash.nix

Backport from upstream release-20.09 branch.

logstash: fix support for multiple plugin paths

---

nixos/lib/test-driver/test-driver.py

Backport of
https://github.com/NixOS/nixpkgs/commit/a874235dff32bd77125034cfd9542a91b68efb03
to 20.09

Clean up serial thread

---

pkgs/development/compilers/go/1.15.nix

go_1_15: require big-sur system-feature.

---

pkgs/development/interpreters/python/cpython/3.9/darwin-tcl-tk.patch
pkgs/development/interpreters/python/cpython/default.nix

python39: fix tkinter and decimal on aarch64-darwin

[awake-21.05] Merge pull request #133847 from angustrau/python-tkinter-aarch64-darwin

---

maintainers/maintainer-list.nix
pkgs/development/python-modules/python-arango/default.nix
pkgs/top-level/python-packages.nix

pythonPackages/python-arango: init at 7.5.0

---

pkgs/development/python-modules/python-arango/default.nix
pkgs/top-level/python-packages.nix

Forward port of https://github.com/awakesecurity/nixpkgs/pull/52

[21.05] python3Packages.python-arango: init at 7.5.0

---

nixos/lib/make-disk-image.nix
nixos/lib/testing-python.nix
nixos/modules/virtualisation/qemu-vm.nix
nixos/tests/containers-bridge.nix
nixos/tests/containers-extra_veth.nix
nixos/tests/containers-imperative.nix
nixos/tests/containers-ip.nix
nixos/tests/containers-portforward.nix
nixos/tests/containers-tmpfs.nix

To facilitate nixos-tests that rely on an isolated store in our 21.05 pin

[21.05] Backport useNixStoreImage qemu option.

---

pkgs/servers/nosql/arangodb/default.nix
pkgs/top-level/aliases.nix
pkgs/top-level/all-packages.nix

Backport arango@3.10.0
CC  @adarshb20

[awake-21.05] Backport arangodb upgrade

---

pkgs/servers/nosql/redis/default.nix

Redis package forwardport to 21.11

---

nixos/modules/system/boot/systemd.nix

To avoid the situation where a service unit file may have a [Unit] but no valid [Service].
For now emit a warning as this could be a breaking change.

[21.11] nixos/systemd: check that services actually run something

---

pkgs/misc/vim-plugins/vim-utils.nix

Fix syntax error

---

nixos/modules/services/web-servers/minio.nix
pkgs/servers/minio/default.nix
pkgs/top-level/all-packages.nix

To avoid future migration issues.

[21.05] Backport minio package and service changes.

---

pkgs/development/python-modules/pybind11/default.nix
pkgs/development/python-modules/pybind11/setup-hook.sh

```
8f658696eac495365d1da456249548a2406ae0a1 \
f9c2ed0713296a247bec8f142f32c479e1a2dcd1 \
f1689bd490619ed3d96a96bb2d688eedd6079e79 \
be1609fe569f507c12ea8eede34ea1612ae69009 \
dd3d4171471b8bbd58550ca412c66dc54771fedf \
20b0221ec3e97cfce9778df834c7311d34239522 \
9af0939eae988eae736a7c2a0d539be4d2d7630a \
3bb4b724b46a46af0fb04946b8f9d150f1c8eb4d \
1725792452dc9c2e095acf426fbb6a9f1f741680 \
89dcf2c639a45974161178284aa40d7c583b0610 \
3f623f2b19c52fd639f3e4457cd2252ce64f446a \
19c5ad8058d5423140fcd6c77584b4eadc38c6f2 \
81465ba9497e05a3ef1c1dcb6a15223ca1cfa2a1 \
3758641dd44cb05b4c67cb12f165a2e97b374a1e \
4ddfd5f74d3e14582aec99d0cec48ff046ee358b \
c8ddde75f78d3b00c941bf14fa686ddf99c9b9e1 \
7f8f688ef3d340c50ac47445081ffa1c69449c0c
```
+there were two treewide commits that I …

[21.11] python3Packages.pybind11: 2.8.0 -> 2.10.4

---

pkgs/development/libraries/rdkafka/default.nix

```
cab6e3395ad407687e6fd3b9a1b33ef071caa4c9 \
92ee92f7832bc151995790ae11a79f9b06677d62 \
a00109285cde26ce801fb780086622f82f6e32de \
251d1f770923b12653f5da4f529867248ea9228e
```

[21.11] rdkafka: 1.8.0 -> 2.0.2

---

pkgs/development/tools/database/liquibase/default.nix

technically redundant jars here, but this is the fastest fix

Fix liquibase jar structure

---

nixos/modules/services/system/self-deploy.nix

Had to partially backport treewide fix. Hopefully that is ok

Backport self deploy fix

---

pkgs/tools/security/spire/default.nix

fix spire merge

---

pkgs/development/python-modules/pymisp/default.nix
pkgs/development/python-modules/pymisp/pymisp-remove-poetry-group.patch
pkgs/top-level/python-packages.nix

This PR adds the pymisp package - https://pymisp.readthedocs.io/en/latest/ to the list of python packages.

python3Packages.pymisp: init at 2.4.174

---

pkgs/servers/sql/postgresql/ext/pg_ivm.nix
pkgs/servers/sql/postgresql/packages.nix

```
a895a0b3ada453f3e7d3ecc422edc2e172efb5fe \
8d807a1026457b4963ba91d24201bf83575cb5dc \
b3f1fee9401466faa76a0b2d5923f770eebd2d0c \
62ad474f0ff81f22f6db31e44b289b973e69b522 \
12d836730a81d008b93c4eb2e0faa0857a260c1d
```
this applies cleanly

Backport postgresql ivm extension

---

pkgs/development/python-modules/wikipedia-api/default.nix
pkgs/top-level/python-packages.nix

```
git cherry-pick 0ea03f139c5ab4abd5fd96723ecb1735d0c99aae
```

[backport] python3Packages.wikipedia-api: init at 0.6.0

---

pkgs/development/python-modules/treelib/default.nix
pkgs/top-level/python-packages.nix

```
git cherry-pick 187496d97f234dd1e91de1366788f5373172b62d
```

[backport] python3Packages.treelib: init at 1.7.0

---

pkgs/development/python-modules/aiohttp-basicauth/default.nix
pkgs/development/python-modules/aioprometheus/default.nix
pkgs/development/python-modules/pydata-sphinx-theme/default.nix
pkgs/development/python-modules/quantile-python/default.nix
pkgs/development/python-modules/quart/default.nix
pkgs/top-level/python-packages.nix

```
50825202d73ba82541dd564754fb01d6e65e22da \
14c9c309823b248aa352d92ed519823c01a1d4de \
175db3dcf32dc92566f56a805c87d2e7ada72cb3 \
7e922ee6e0917c9c76a93f8d730907fc88d4adf7 \
4216f2bf0648eb276d65e75419f4ee89b00083be
```

[backport] python3Packages.aioprometheus: init at unstable-2023-03-14

---

pkgs/tools/networking/unbound/default.nix

Fixes:
* CVE-2022-30698
* CVE-2022-30699
* CVE-2022-3204

unbound: 1.14.0 -> 1.16.2

---

pkgs/os-specific/linux/sysstat/default.nix

Fixes:
* CVE-2022-39377
* CVE-2023-33204

sysstat: 12.4.5 -> 12.7.4

---

pkgs/servers/consul/default.nix

Fixes:
* CVE-2021-41803
* CVE-2021-41805
* CVE-2022-24687
* CVE-2022-29153
* CVE-2022-40716
* CVE-2023-0845

consul: 1.12.1 -> 1.15.0

---

pkgs/development/libraries/libtasn1/default.nix

libtasn1: 4.18.0 -> 4.19.0

---

pkgs/tools/networking/curl/7.79.1-darwin-no-systemconfiguration.patch
pkgs/tools/networking/curl/7.87.0-noproxy-tailmatch.patch
pkgs/tools/networking/curl/CVE-2022-43551.patch
pkgs/tools/networking/curl/CVE-2022-43552.patch
pkgs/tools/networking/curl/CVE-2023-23915.patch
pkgs/tools/networking/curl/CVE-2023-23916.patch
pkgs/tools/networking/curl/CVE-2023-27533.patch
pkgs/tools/networking/curl/CVE-2023-27534.patch
pkgs/tools/networking/curl/CVE-2023-27535.patch
pkgs/tools/networking/curl/CVE-2023-27536.patch
pkgs/tools/networking/curl/CVE-2023-27537.patch
pkgs/tools/networking/curl/CVE-2023-27538.patch
pkgs/tools/networking/curl/CVE-2023-28319.patch
pkgs/tools/networking/curl/CVE-2023-28320.patch
pkgs/tools/networking/curl/CVE-2023-28321.patch
pkgs/tools/networking/curl/default.nix
pkgs/tools/networking/curl/netrc-regression.patch
pkgs/tools/package-management/nix/common.nix
pkgs/tools/package-management/nix/default.nix
pkgs/top-level/all-packages.nix

Fixes:
* CVE-2022-27779
* CVE-2022-27780
* CVE-2022-27781
* CVE-2022-27782
* CVE-2022-30115
* CVE-2022-32205
* CVE-2022-32206
* CVE-2022-32207
* CVE-2022-32208
* CVE-2022-32221
* CVE-2022-35252
* CVE-2022-42915
* CVE-2022-42916
* CVE-2022-43551
* CVE-2022-43552
* CVE-2023-23914
* CVE-2023-23915
* CVE-2023-23916
* CVE-2023-27533
* CVE-2023-27534
* CVE-2023-28319
* CVE-2023-28320
* CVE-2023-28321

curl: 7.83.1 -> 7.86.0

---

pkgs/development/python-modules/pyrate-limiter/default.nix
pkgs/development/python-modules/requests-ratelimiter/default.nix
pkgs/top-level/python-packages.nix

cherry pick command:
```
d1c01ddce4d91bebffd8c6aebdac69605d7cfe63 \
dede93fc179b2cc7803505529ebd967b043613f2
```

[backport] python3Packages.requests-limiter: init at 0.4.2

---

pkgs/tools/networking/curl/CVE-2023-38545.patch
pkgs/tools/networking/curl/default.nix

see https://curl.se/docs/CVE-2023-38545.html

curl: fix CVE-2023-38545

---

pkgs/development/libraries/nettle/default.nix

nettle: 3.7.3 -> 3.9.1

---

pkgs/development/python-modules/wheel/0001-tests-Rename-a-a-o-_-.py-_-.py.patch
pkgs/development/python-modules/wheel/default.nix

python310Packages.wheel: 0.37.1 -> 0.38.4

---

pkgs/development/libraries/atk/default.nix
pkgs/development/libraries/gdk-pixbuf/default.nix
pkgs/development/libraries/geoclue/default.nix
pkgs/development/libraries/gstreamer/bad/default.nix
pkgs/development/libraries/gstreamer/base/default.nix
pkgs/development/libraries/gstreamer/core/default.nix
pkgs/development/libraries/gstreamer/devtools/default.nix
pkgs/development/libraries/gstreamer/ges/default.nix
pkgs/development/libraries/gstreamer/good/default.nix
pkgs/development/libraries/gstreamer/libav/default.nix
pkgs/development/libraries/gstreamer/rtsp-server/default.nix
pkgs/development/libraries/gstreamer/ugly/default.nix
pkgs/development/libraries/gstreamer/vaapi/default.nix
pkgs/development/libraries/gtk/3.x.nix
pkgs/development/libraries/harfbuzz/default.nix
pkgs/development/libraries/json-glib/default.nix
pkgs/development/libraries/libgudev/default.nix
pkgs/development/libraries/libical/default.nix
pkgs/development/libraries/libmanette/default.nix
pkgs/development/libraries/libsecret/default.nix
pkgs/development/libraries/libsoup/default.nix
pkgs/development/libraries/pango/default.nix
pkgs/development/libraries/polkit/default.nix
pkgs/development/libraries/tracker/default.nix
pkgs/tools/networking/networkmanager/default.nix

Fixes:
* CVE-2022-1920
* CVE-2022-1921
* CVE-2022-1922
* CVE-2022-1923
* CVE-2022-1924
* CVE-2022-1925
* CVE-2022-2122

gstreamer: 1.20.0 -> 1.20.3

---

pkgs/development/python-modules/anyio/default.nix
pkgs/development/python-modules/httpcore/default.nix
pkgs/development/python-modules/httpx/default.nix
pkgs/development/python-modules/multipart/default.nix
pkgs/top-level/python-packages.nix

Needed for https://awakesecurity.atlassian.net/browse/MONAPP-34316
```
git cherry-pick c26c5a4371dc2107fd127131390ae69b5fb051ff 00211043444e19c717ac741278c8604115129d88 f59a206a68f393388f8ba1feeae3d00af3f35fda 2a9bccc5cb63bd74f5b6f1a898b47159355e7ce9
```

python3Packages.httpcore: 0.15.0 -> 0.16.2

---

pkgs/development/python-modules/anyio/default.nix
pkgs/development/python-modules/hatch-fancy-pypi-readme/default.nix
pkgs/development/python-modules/httpcore/default.nix
pkgs/development/python-modules/httpx/default.nix
pkgs/development/python-modules/multipart/default.nix
pkgs/top-level/python-packages.nix

Backport for release 5.1 of https://github.com/awakesecurity/nixpkgs/pull/184
```
git cherry-pick 99ecb8ded55ac57929d4e8b462bd3a81d81bd2a8 c26c5a4371dc2107fd127131390ae69b5fb051ff 00211043444e19c717ac741278c8604115129d88 d028f1ee858df6d4da01cff2413d1eeb35b186ef f59a206a68f393388f8ba1feeae3d00af3f35fda 2a9bccc5cb63bd74f5b6f1a898b47159355e7ce9 b0beaa821ed622df8783f01ce0f15fdc0a779931
```

[Backport-5.1] python3Packages.httpcore: 0.15.0 -> 0.16.2

---

nixos/modules/services/monitoring/datadog-agent.nix

`git cherry-pick 7fe4909bee9864df3d4bc196cb337aebaae32153`

services.datadog: remove python2 from systemd service

---

pkgs/development/compilers/openjdk/openjfx/11.nix
pkgs/development/compilers/openjdk/openjfx/15.nix
pkgs/development/compilers/openjdk/openjfx/17.nix
pkgs/top-level/all-packages.nix

```
53256fcdb5a0dfb6e3c27eb7d73bf2527342a625 \
e7bce809ef956ab9b8cd58976ea511def621b07a \
b51a1d1f67516591fe84b2a8d53e7b9f0130bddd \
9e5e9c57bb8958004134806eef8e31aed9375ea6 \
61de80e49901ba60f1d3c4c587b17fb77964102c \
640c102321b244edb0b2156cd27ecb16620bd19c \
976849f2e693549ce96a65ae75c5a3c03e5742fb
git cherry-pick 6145b7c77057794c8e8262c24ae2e0819009ca36
```

Upgrade openjfx

---

pkgs/development/python-modules/pytest-mypy-plugins/default.nix
pkgs/development/python-modules/returns/default.nix
pkgs/top-level/python-packages.nix

Cherry pick: 
```
git cherry-pick 08e5e2185ddafb11b3ff75fdf9e87b7aa31581bd \
02a8373229448a6df8c7318628b64816c2698318 \
260d2c71447bf1ec197b9cb743d40953cbd7b82d \
cb28b010b1a3c6a5d969abfbba06ddc95084d721
```

python3Packages.returns: init at 0.19.0

---

pkgs/tools/networking/openssh/common.nix
pkgs/tools/networking/openssh/openssh-CVE-2023-48795.patch

[5.1] openssh: fixup for terrapin / CVE-2023-48795

---

nixos/modules/services/infrastructure/terraform-cloud-agent/default.nix

This change adds NixOS options for configuring a set of pre and post hooks for the Terraform Cloud Agent to run around planning and applying.

terraform-cloud-agent: support tfc-agent hooks

---

pkgs/development/python-modules/types-psycopg2/default.nix
pkgs/top-level/python-packages.nix

In the end only `types-psycopg2` was needed

python3Packages.types-psycopg2: init at 2.9.21.20240417

---

pkgs/build-support/trivial-builders.nix
pkgs/top-level/all-packages.nix
pkgs/top-level/stage.nix

backport shellcheck-minimal

---

pkgs/tools/misc/grub/2_06.nix
pkgs/top-level/all-packages.nix

workaround for https://github.com/NixOS/nixpkgs/issues/293038

[DOWNGRADE] grub2: 2.12-rc1 -> 2.06

---

pkgs/development/tools/pandoc/default.nix

 pandoc: remove GHC & haskell deps from closure, 5.2G => 250M

---

pkgs/development/libraries/openssl/3.3/CVE-2024-5535.patch
pkgs/development/libraries/openssl/default.nix

```
226f3574fbd590c7f35c7265f9cb27996070ce3b \
1bd767f56b3bd666721f0f1ae90328406dcfee37 \
97c9e3ab780b08c2804dc1a81f88f1887d200182 \
ccaad56e4b7d3fb3c7b461ef3d43045992b54e5f \
29ee41feff51c3269c2c160fa4d67de6ba5cca36 \
90b11e4031a6d1236657d7509ff0790ea4285712 \
38f10f915a4bed4dd392d4fe411106e5842f4013 \
6fef5775cc1b70729e1526086c72c8fbaf584002
```

openssl_3: 3.0.10 -> 3.0.15

---

nixos/lib/systemd-lib.nix
nixos/modules/services/hardware/udev.nix
nixos/modules/services/logging/journalwatch.nix
nixos/modules/system/activation/top-level.nix
nixos/tests/hydra/common.nix
pkgs/build-support/build-fhsenv-chroot/env.nix
pkgs/build-support/emacs/wrapper.nix
pkgs/development/libraries/dbus/make-dbus-conf.nix
pkgs/development/libraries/fontconfig/make-fonts-cache.nix

This reverts commit ce06d814ed857c490426527f4b298cbf1d05d4b6.
Superceaded by --omit-local snowkite option

Revert "mark trivial derivations with __snowkiteOmissible"

---

pkgs/servers/sql/postgresql/ext/pg_partman.nix

```
git revert 6c4399a7722841451ccb5f92da4f4ee19bcd520f 566da4292397ca81414953938761d3f80bde4645 01519149654edcc568f7a881ffe7de7d0b197eff`
7695b70193a46586e209bf1c4e4968b6aa93327f \
bf171199a07438fa62480d43323eb375e8642a22 \
9ce6259fd13ec7ce0e9eeec214e9d0f626a913a1
```

pgPackages.pg_partman: 4.7.4 -> 5.2.4
