awakesecurity/nixpkgs

- nixos/lib/testing.nix
The NixOS test log files might not necessarily be present, in
situations like:
* The test finishes before a VM boots up
* A VM is shutdown before the test finishes
To handle those scenarios, we gracefully ignore log
directories that are missing when exporting them to the final
build product.
> Fix support for exporting logs

- nixos/modules/services/monitoring/datadog-agent.nix
- pkgs/tools/networking/dd-agent/6.nix
- pkgs/tools/networking/dd-agent/datadog-trace-agent-deps.nix
- pkgs/tools/networking/dd-agent/datadog-trace-agent.nix
- pkgs/top-level/all-packages.nix
This backports debbed29d1da582e75ebf266b203baad063550c3
and 35d58c3421fea71394fa3b3e8c10bd862d76f3d8 to Nixpkgs 18.09
so that we can start using the DataDog upstream
> Backport Datadog fixes

- pkgs/development/python-modules/apache-airflow/default.nix
Backport of e240c5 to `release-20.03`
> apache-airflow: Export PYTHONPATH in wrapper for gunicorn processes

- nixos/modules/system/boot/systemd.nix
We upgraded `systemd` to handle `Restart=on-failure` for `oneshot`
services, so this warning is inaccurate
> Disable warning for `oneshot` services

- pkgs/development/compilers/llvm/5/compiler-rt.nix
- pkgs/development/compilers/llvm/6/compiler-rt.nix
I made a mistake when cherry-picking
c3c27f7d36e0eff38e896891d643c4e9d8231b3d
onto the `release-20.03` branch to create
1e5a44e035ed2294e7fef22cdcf9bf966a6a6c00.
Specifically, I accidentally cherry-picked what should have been
a `cmakeFlags` flag as part of the `configureFlags` for some of the
`compiler-rt` builds, which this change fixes.
> Fix build for `compiler-rt-{5,6}.*.*

- nixos/lib/build-vms.nix
- nixos/lib/testing.nix
This upstreams https://github.com/awakesecurity-dev/end-to-end/blob/d005f355c4b51cf39b54e34ecad89d98c6c7f279/awake-pkgs/nixpkgs/nixos-19_09.patch
into our vendored Nixpkgs.  Doing so greatly simplifies the patch
because we no longer need to thread through a `nixpkgs` argument.
We also never needed to patch `./nixos/default.nix` as we were not
using that file at all.
> Patch through support for `specialArgs`

- pkgs/development/haskell-modules/with-packages-wrapper.nix
This cherrypicks 32d2de8e0092864cb0a9dfe68ea67a813e0e600e onto `awake-20.03`
`with-packages-wrapper.nix` has a hack to workaround the linker limit
in MacOS Sierra. However that is now broken with GHC 8.8, because of
slight change in the format of the package config.
In short, the package config produced by GHC 8.8 has a new line between
the key and list of values, while earlier versions have them separated
by a single space.
This PR fixes the linker hack by modifying the `grep` and `sed` commands
to pattern match on either space or new line, so that the hack can work
on all versions of GHC.
> haskell: Fix with-packages-wrapper MacOS linker hack for GHC 8.8

- pkgs/tools/system/collectd/plugins.nix
The `release-20.03` branch claims to support Nix version 2.0 or greater
in `./lib/minver.nix`, but at least one place uses `builtins.concatMap`,
which is not present in Nix 2.0.4.
This fixes that by using `lib.concatMap`, which will fall back to
`builtins.concatMap` if it is present.
> Support Nix 2.0.4

- nixos/lib/testing-python.nix
Applies the change Gabriel introduced in <https://github.com/awakesecurity/nixpkgs/commit/69d1771fb09f9704717bdc1a2fd2d66b93f3d48d> to the Python test driver.
> Patch in `specialArgs` to Python test driver

- nixos/modules/config/system-path.nix
readd perl (used in shell scripts), rsync (needed for NixOps) and strace (common debugging tool)
they where previously removed in https://github.com/NixOS/nixpkgs/pull/91213
Co-authored-by: Timo Kaufmann <timokau@zoho.com>
Co-authored-by: 8573 <8573@users.noreply.github.com>
> nixos/config: add defaultPackages option

- nixos/lib/test-driver/test-driver.py
- nixos/lib/testing-python.nix
Backport of 8ee31be5dd60a3bd975e77511b0bdcfe54f18a82
> nixos/testing: add interactive serial stdout logs switch and dim them

- nixos/lib/test-driver/test-driver.py
- nixos/lib/testing-python.nix
This allows the user to log into a machine from the NixOS interactive test driver by running `machine.shell_interact()`
> Backport `shell_interact` method for NixOS test driver

- nixos/lib/test-driver/test-driver.py
- nixos/lib/testing-python.nix
This allows the user to log into a machine from the NixOS interactive test driver by running `machine.shell_interact()`
This is the same as #20, except backported to `awake-20.09`
> Backport `shell_interact` method for NixOS driver

- nixos/modules/system/boot/tmp.nix
Backport of 56d7e7492cbf2d61bd570f5b0a8015040e80aae9 to `awake-20.09`
> nixos/tmp: Make /tmp on ramdisk usable again

- nixos/modules/system/boot/tmp.nix
Backport of ca7b35d2d9c276cf08d9ca8248eae004f4e9d295 to `awake-20.09`
Related to https://awakesecurity.atlassian.net/browse/MONAPP-26471
> modules/boot: Specify the type for tmpfs mounts

- nixos/modules/services/monitoring/telegraf.nix
The `merge` for attrs would cause `inputs`, `outputs`,
etc. configuration values to be clobbered by other modules. `attrsOf`
with some slightly more precise subtypes allows better merging.
The downside is the type may have to change if telegraf changes its
config format, but it seems pretty stable. (sic, on fork only, upstream
uses the toml type)
> telegraf: Better merging of configuration.

- nixos/modules/installer/tools/nixos-install.sh
Fixes https://awakesecurity.atlassian.net/browse/MONAPP-27168
`make-disk-image` was hanging in the middle of the `nixos-install`
step:
https://github.com/NixOS/nixpkgs/blob/41c440bebe969c5fc70c97f6b95536b33d50b152/nixos/lib/make-disk-image.nix#L279-L282
… specifically the `nix-env` sub-step:
https://github.com/NixOS/nixpkgs/blob/e6f82bab843bd083cc7b46448a3a73809791713f/nixos/modules/installer/tools/nixos-install.sh#L165-L167
… if an auto-GC was triggered via the min-free option in the middle
of that step.  The fix is to disable `min-free` during a `nixos-install`
to prevent this from happening.
> nixos-install: Disable min-free

- pkgs/development/python-modules/apache-airflow/default.nix
There is a broken migration in Airflow.
In the end I've made issue and PR to the Airflow repo, so until it gets merged I've added a patch here.
Already deployed on test instance - it should be working.
> Fix airflow migration - 21.05/Airflow 2.3.2

- pkgs/development/python-modules/apache-airflow/default.nix
This ensures stable hash, which broke during rebasing the original PR.
> Change apache-airflow patch from PR to commit.

- nixos/modules/services/web-apps/keycloak.nix
This is necessary to shut the keycloak server process tree down.
Co-authored-by: Raghu Kaippully <raghuk@arista.com>
> nixos/keycloak: always exit success

- pkgs/development/compilers/rust/cargo.nix
- pkgs/development/compilers/rust/rustc.nix
> rustc, cargo: always build on big-sur

- nixos/modules/services/misc/nix-daemon.nix
To allow users to select ssh or ssh-ng.
> nixos/nix-daemon: add protocol configuration for buildMachines

- pkgs/development/python-modules/aiopg/default.nix
- pkgs/development/python-modules/anyio/default.nix
- pkgs/development/python-modules/azure-core/default.nix
- pkgs/development/python-modules/azure-cosmos/default.nix
- pkgs/development/python-modules/cryptography/default.nix
- pkgs/development/python-modules/cryptography/vectors.nix
- pkgs/development/python-modules/databases/default.nix
- pkgs/development/python-modules/fastapi/default.nix
- pkgs/development/python-modules/importlib-resources/default.nix
- pkgs/development/python-modules/llvmlite/default.nix
- pkgs/development/python-modules/numba/default.nix
- pkgs/development/python-modules/parameterizedtestcase/default.nix
- pkgs/development/python-modules/python-jose/default.nix
- pkgs/development/python-modules/smart-open/default.nix
- pkgs/development/python-modules/starlette/default.nix
- pkgs/development/python-modules/textacy/default.nix
- pkgs/development/python-modules/typing-extensions/default.nix
- pkgs/development/python-modules/typing-inspect/default.nix
- pkgs/top-level/python-packages.nix
Backport changes to several packages that are generally incompatible with each other on NixOS/nixpkgs release-21.05
* aiopg
* anyio
* azure-core
* azure-cosmos
* cryptography
* database
* databases
* fastapi
* importlib-resources
* llvmlite
* numba
* parameterizedtestcase
* python-jose
* smart-open
* starlette
* textacy
* typing
* typing-extensions
* typing-inspect
> python3Packages: Backport several packages

- nixos/modules/services/system/self-deploy.nix
Without `gnutar` and `gzip` on the path of the service, it fails.
> [backport awake-21.05] self-deploy fixes

- pkgs/development/python-modules/httplib2/default.nix
To fix test failures on darwin.
Cherry picked from NixOS/nixpkgs release-21.11 ^release-21.05, no merges.
> [awake-21.05] fix httplib2 on darwin (backports)

- pkgs/tools/admin/gixy/default.nix
(this does not apply to awake-21.05) Backport gixy python dependency update in an effort to reduce closure size.
> gixy: use python3

- pkgs/development/python-modules/apache-airflow/default.nix
- pkgs/development/python-modules/sh/disable-broken-tests-darwin.patch
- pkgs/development/tools/misc/binutils/bfd-elf-Dont-read-non-existing-secondary-relocs.patch
- pkgs/development/tools/misc/binutils/default.nix
- pkgs/development/tools/misc/binutils/gold-Update-GNU_PROPERTY_X86_XXX-macros.patch
Backports https://github.com/NixOS/nixpkgs/pull/129900 and https://github.com/NixOS/nixpkgs/pull/134195 to fix `strip` performance regression and ghc linkage fallout.
> [21.05] binutils: backport performance/regression fixes.

- nixos/modules/services/system/self-deploy.nix
Primarily to install the timer alongside the service.
> [21.05] nixos/self-deploy: backport fixes from upstream.

- nixos/modules/services/monitoring/grafana-image-renderer.nix
Add the before of grafana in grafana-image-renderer.nix, with this change, the before can be deleted in awake-grafana.nix.
> Added before for grafana in grafana-image-renderer.nix

- pkgs/build-support/trivial-builders.nix
- pkgs/build-support/trivial-builders/test/sample.nix
We would like to use `empty{File,Dir}` in some cases in the 21.05 branch. This backports them from upstream.
> [awake-21.05] Backport emptyFile, emptyDir

- lib/cli.nix
mkForce/mkOverride place the desired content in the "content" attribute of an attrset, often changing the type of the option.
By default "toGNUCommandLine" will now unwrap such a wrapped value instead of failing, though overrides to "mkOption" option will change this behavior and may add other support for attrsets.
Command line options are commonly based on NixOS options, and those are often overridden by mkForce/mkOverride.  When this happens the new values are attrsets and cause command line rendering to fail.  This change avoids that problem by default, while preserving generality by modifying only the default behavior.
> toGNUCommandLine: Unwrap value if set by mkForce/mkOverride

- pkgs/development/python-modules/python-arango/default.nix
python-arango 7.5.1 is the minimum version supported arangodb 3.10.X
> python3Packages.python-arango: 7.5.0 -> 7.5.3

- lib/cli.nix
A wrapped boolean or list value would not
have processed using mkBool or mkList.
> toGNUCommandLine: Fix bug in unwrapping of values.

- lib/cli.nix
> lib/cli.nix: fix typo.

- nixos/tests/kafka.nix
- pkgs/servers/apache-kafka/default.nix
- pkgs/top-level/all-packages.nix
Apache kafka update to the latest version (backport from nixpkgs 22.11). I don't think it should break something, but I'll test it on the 'end-to-end' to be sure and let you know @jsoo1.
> Apache Kafka backport - awake 21.05

- pkgs/development/python-modules/python-arango/default.nix
Backporting the python-arango driver from upstream.
CC @adarshb20
> [awake-21.05] backport python3Packages.python-arango: init at 7.5.3

- nixos/modules/services/system/self-deploy.nix
- nixos/tests/kafka.nix
- pkgs/applications/editors/uivonim/default.nix
- pkgs/applications/networking/browsers/vieb/default.nix
- pkgs/build-support/trivial-builders.nix
- pkgs/development/compilers/rust/rustc.nix
- pkgs/development/python-modules/azure-core/default.nix
- pkgs/development/python-modules/azure-cosmos/default.nix
- pkgs/development/python-modules/cron-descriptor/default.nix
- pkgs/development/python-modules/flask-session/default.nix
- pkgs/development/python-modules/linkify-it-py/default.nix
- pkgs/development/python-modules/python-arango/default.nix
- pkgs/development/python-modules/spacy/default.nix
- pkgs/development/python-modules/spacy/legacy.nix
- pkgs/development/python-modules/spacy/models.json
- pkgs/development/python-modules/typing-extensions/default.nix
- pkgs/development/tools/yarn2nix-moretea/yarn2nix/default.nix
- pkgs/development/tools/yarn2nix-moretea/yarn2nix/internal/fixup_yarn_lock.js
- pkgs/development/tools/yarn2nix-moretea/yarn2nix/lib/generateNix.js
- pkgs/servers/apache-kafka/default.nix
- pkgs/servers/nosql/arangodb/default.nix
- pkgs/tools/admin/awscli2/default.nix
- pkgs/tools/misc/sharedown/default.nix
- pkgs/top-level/aliases.nix
- pkgs/top-level/all-packages.nix
- pkgs/top-level/python-packages.nix
To get:
* Fixed awscli2
* airflow 2.4.1
* up-to-date python3Packages.azure-{cosmos,core}
* up-to-date python3Packages.typing-extensions
* rust fixes
* writeShellApplication fixes
* arangodb updates
* python-arango
* kafka 3.x
> [awake-21.11] Upstream backports

- nixos/modules/services/databases/redis.nix
- pkgs/servers/nosql/redis/default.nix
Redis 7.0.0 package backport. We would like to use redis for Device Identification Improvement project
All tests passed @jsoo1 
https://buildkite.com/awakesecurity/end-to-end/builds/78536
> Redis package backport

- pkgs/stdenv/generic/default.nix
To fix `writeShellApplication` which uses `shellDryRun` on the revision we prefer.
> [awake-21.11] stdenv/generic: introduce shellDryRun

- pkgs/stdenv/generic/default.nix
To fix `writeShellApplication` which uses `shellDryRun` on the revision we prefer.
> [awake-21.05] stdenv/generic: introduce shellDryRun

- pkgs/os-specific/linux/libcgroup/default.nix
Co-authored-by: Sandro <sandro.jaeckel@gmail.com>
> [21.11] backport libcgroup: 0.42.2 -> 2.0.2 (#185260)

- pkgs/os-specific/linux/libcgroup/default.nix
Co-authored-by: Sandro <sandro.jaeckel@gmail.com>
> [21.05] backport libcgroup: 0.42.2 -> 2.0.2 (#185260)

- nixos/modules/system/boot/systemd.nix
To avoid the situation where a service unit file may have a [Unit] but no valid [Service].
> [21.05] nixos/systemd: check that services actually run something

- nixos/modules/services/networking/nghttpx/default.nix
- nixos/modules/services/networking/nghttpx/nghttpx-options.nix
To configure necessary timeouts and parameterize user/group.  nghttpx was upstreamed and this is all that remains of the diff.
> [21.11] nixos/nghttpx: parameterize user, require timeouts

- pkgs/misc/vim-plugins/vim-utils.nix
... so that their `bin`'s are populated with the convenience symlinks that people expect.
This change also adds an assertion reminder to remove the e7bfb04 changes once we upgrade to a `nixpkgs` > 21.11.
> vim-utils: add `vi` and `gvi` symlinks to vim wrapper scripts

- pkgs/misc/vim-plugins/vim-utils.nix
... so that their `bin`'s are populated with the convenience symlinks that people expect.
This change also adds an assertion reminder to remove the e7bfb04 changes once we upgrade to a `nixpkgs` > 21.11.
Forward port of #90.
> [21.11] vim-utils: add `vi` and `gvi` symlinks to vim wrapper scripts

- nixos/modules/services/web-servers/minio.nix
Otherwise `minio.service` will fail either:
* with a message that the EnvironmentFile does not exist
* or silently with potentially stale credentials
> nixos/minio: gracefully handle root credentials file

- nixos/modules/services/web-servers/minio.nix
Otherwise `minio.service` will fail either:
* with a message that the EnvironmentFile does not exist
* or silently with potentially stale credentials
> [21.11] nixos/minio: gracefully handle root credentials file

- pkgs/build-support/buildenv/default.nix
> buildenv: allow substitutes for `buildEnv`s

- pkgs/build-support/buildenv/default.nix
> [21.11] buildenv: allow substitutes for `buildEnv`s

- pkgs/development/python-modules/black/default.nix
Bumping `black` to 22.3.0, which is the version we use to check our Python sources formatting.
> Tomask/bump black to 22.3.0

- pkgs/development/python-modules/frozendict/default.nix
Another batch of python backports
```
3dffd60b206b07b087ce1d589d2fccfe107cd342 \
7f9f1ecd900c163362b69685ec6d799edcdbb334 \
f8628e91abeefa1ab908ed1e105df6b4cd9372b9 \
b7ca8b4a64783d6465552e53c73affe163f64649 \
113346fed8c97db4b4dda7352eb6d1b960fbfeac \
810249eb77f873de38b8ea2ab0c750dcae8b2e5c \
80fd713fe6d7bb9f0247e1f967046ce6889c18dd \
4b9c71f4a5c23360410f27c7573eb01a6e48ff11 \
bff5824e32b934aa3766e23ce389b1490976cde9 \
44d41315bf315223342effb46aa9c16e97442673 \
7c8c39c8faebdc006c2ef1e99e4527ab4825d86d
```
https://github.com/NixOS/nixpkgs/commit/687b1233c24e3f3661a6ecaa74b9bbf08454f0df was already present
> [21.11] python3Packages.frozendict: 2.0.7 -> 2.3.4

- pkgs/development/python-modules/boto3/default.nix
- pkgs/development/python-modules/botocore/default.nix
- pkgs/development/python-modules/moto/default.nix
- pkgs/tools/admin/awscli/default.nix
For better IT we need newer version of python `moto`  (AWS services mocks). In this PR we bump `moto` version and some dependencies `boto3`, `botocore`, `awscli`. These changes were cherry-picked from `22.05` tag in original `nixpkgs` repository.
> Bump moto version and its dependencies

- nixos/lib/build-vms.nix
This is a backport from https://github.com/NixOS/nixpkgs/pull/235874
> build-vms: keep support for lib overlays

- pkgs/development/tools/database/liquibase/default.nix
Liquibase 4.17.2 uses a different, newer command line runner that accepts new arguments. This changes that packaging to use that method
> Use newer main method

- nixos/modules/services/continuous-integration/buildkite-agents.nix
Backport of https://github.com/NixOS/nixpkgs/pull/236778
So that we can shellcheck hooks and use new hooks.
> nixos/buildkite-agents: simplify agent module.

- pkgs/top-level/python-packages.nix
During a recent nixpkgs update, tensorflow got updated to 2.7.0, but we missed passing overridden `protobuf-core` and `protobuf-python`.
> tensorflow: pass overridden protobuf packages

- lib/default.nix
- lib/meta.nix
It turns out it was added in April '22, so we don't have it yet
> Backport `lib.getExe`

- doc/stdenv/platform-notes.chapter.md
- pkgs/development/compilers/go/1.19.nix
- pkgs/development/compilers/go/skip-cgo-tests-1.19.patch
- pkgs/development/compilers/go/skip-chown-tests-1.16.patch
- pkgs/os-specific/darwin/apple-sdk-11.0/apple_sdk.nix
- pkgs/os-specific/darwin/apple-sdk-11.0/default.nix
- pkgs/top-level/all-packages.nix
- pkgs/top-level/darwin-packages.nix
Backported the following commits for go-1.19.1
- af3cd7c1f80738cc6ef4512cfa8d0bbfc45a88db - go: Fix the build in non-root sandboxes
- 80ffac409746c8b3d0696ee96cc25ccf7ac22a27 - Merge pull request #176661 from reckenrode/apple-sdk-11-x86_64
- 168d1c578909dc143ba52dbed661c36e76b12b36 - go_1_19: init at 1.19
- d2d3a9b77ddd01630d51d4c75aa1a49496b41c90 - go_1_19: 1.19 -> 1.19.1
> Backport go-1.19.1

- pkgs/tools/security/spire/default.nix
- Upgrade spire to the latest version - 1.7.0
- ~~This requires go-1.19. I got it working using a configuration similar to 1.17. We can switch to upstream 1.19 when we upgrade to newer versions of nixpkgs.~~
> Add spire-1.7

- doc/stdenv/platform-notes.chapter.md
- pkgs/development/compilers/go/1.19.nix
- pkgs/development/compilers/go/skip-cgo-tests-1.19.patch
- pkgs/os-specific/darwin/apple-sdk-11.0/apple_sdk.nix
- pkgs/os-specific/darwin/apple-sdk-11.0/default.nix
- pkgs/tools/security/spire/default.nix
- pkgs/top-level/all-packages.nix
- pkgs/top-level/darwin-packages.nix
I forgot to get these during the `bump-2023-07-01+f26809c8e485ee492931d9aa63d411c1e01b57ee` update.
See https://github.com/awakesecurity/nixpkgs/pull/123
https://github.com/awakesecurity/nixpkgs/pull/123/commits/9e182932423a65abff0b36b6850655f941bf472d did not apply
> Readd spire 1.7 + go 1.19

- nixos/modules/services/databases/postgresql.nix
Because we don't have mdDoc and friends, yet.
> drop! nixos/postgresql: Remove md documentation functions.

- pkgs/servers/sql/postgresql/default.nix
- pkgs/top-level/all-packages.nix
```
fbe399529890eb555dc547d0f38e4c9ffed22d23 \
b38cf2c9ae0402cb00540397df78d616f371e25f \
621bb272a16599e1bf12d35dffed1840187e3b77 \
940b7d4ee1a1008881f044cdf2986b817c753c42 \
3abafec08f228c6c592c8d7f8b449dff00bdb702
```
But this time cherry-pick wasn't super clean. Change of default PG 13->14, drop of PG 9.6 and JIT support breaks cherry-picking.
I've tried to preserve the commits as much as possible, but we might encounter issues during upgrades
> Backport postgresql 15

- pkgs/development/python-modules/pymisp/default.nix
This PR attempts to resolve the following error
```
error: Module "pymisp"
does not explicitly export attribute "PyMISP"  [attr-defined]
from pymisp import PyMISP
```
A normal install via pip does not yield any errors whereas the version installed via Nix does.
> python3Packages.pymisp: add pythonImportsCheck

- lib/licenses.nix
- pkgs/servers/sql/postgresql/ext/timescaledb.nix
- pkgs/servers/sql/postgresql/packages.nix
This is needed for Postgresql15 support
```shell
06eee30956e6bb2d3dae379e6c0905fcf7e0f2b1 \
6e6a515607b19eb575ba99d7b002b7d4683a5f8d \
4137382abc9786a9e98fea721ffd00ca8de0b883 \
61d95fdcf06052e050182ad347d39b4204b99c57 \
1b8b20bfc0bed52cbdc3e8712d0ce587e3d98cb0 \
56f3cb523ec8224099663f35a0e27a4aabbfc033 \
8e7698746a71b3e927a2f57df3854c6e8e6d24f6 \
64c4077f92dc27b8796739af6b802572e2cc0c7f \
c3aaa8fb5e9ddae0dc3de00cdba200e241ea0f9d \
7e29e1b2c2cb2adb79783f2393553fbfd52175c5 \
4f7f469c8257e136f24bbd2f079e8507790eca57 \
ae5640c0aa013b1d6b246688df53ed8be754d42f \
938afbb96edba3dd28065f5f2d42a86e9714bab3 \
fe3a69ab0c7557224e610ae225bc95fab4603963 \
58ccd88dbd4de7846101322e498d4445e0f00aee \
109f09412752c7108c1bb954ab0cd8921e723094
```
Intentionally left out …
> [backport] postgresqlPackages.timescaledb: 2.6.1 -> 2.11.2

- pkgs/tools/networking/mailsend-go/default.nix
- pkgs/top-level/all-packages.nix
`mailsend` is not receiving any feature updates and we would like its functionality.
> mailsend-go: init at 1.0.10

- nixos/modules/system/boot/systemd.nix
Some service are generated as package outputs instead of by the systemd module. Fix warnings that were inproperly firing for some of those service.
> nixos/systemd: do not emit warning for pkgs service files

- nixos/modules/virtualisation/qemu-vm.nix
This was causing oom issues during builds
see MONAPP-33720
This fix can be dropped once 76c7b656bfa9b20a4172f7901285560db4c2c695 is available
> drop! qemu-vm: Raise memory limit of bootloader build

- pkgs/development/python-modules/pytest-reverse/default.nix
- pkgs/top-level/python-packages.nix
Backport of `pytest-reverse` from upstream. PR: https://github.com/NixOS/nixpkgs/pull/256474
```
git cherry-pick b25543f889b925aa1765b34817e13061b8a23f5d
```
> [backport] python3Packages.pytest-reverse: init at 1.7.0

- pkgs/development/python-modules/huggingface-hub/default.nix
- pkgs/development/python-modules/sentence-transformers/default.nix
- pkgs/top-level/python-packages.nix
We needed to update `huggingface-hub` because of the missing package in `propagatedBuildInputs`. Also, we needed to rename `torch` to `pytorch` as we currently have an older version than upstream.
```
bec4b99baad961400eb64a00a78211debe1e091a \
e9ad7e5feca8a185cb28363b9e33d9fbe7ba6624 \
500b491a25e8f0838c077f528d2cce661df9ecba
```
> [backport] python3Packages.sentence-transformers: init at 2.2.2

- pkgs/development/python-modules/greynoise/0001-drop-ipaddress-from-requirements.patch
- pkgs/development/python-modules/greynoise/default.nix
- pkgs/top-level/python-packages.nix
Not really sure why we need to remove `ipaddress` dependency in our nixpkgs, it was building fine on upstream
```
git cherry-pick b497433b56e2a418d131d82ef849a02491f19851
```
> [backport] python3Packages.graynoise: init at 2.0.1

- pkgs/development/python-modules/aws-secretsmanager-caching/default.nix
- pkgs/development/python-modules/aws-secretsmanager-caching/remove-coverage-tests.patch
- pkgs/top-level/python-packages.nix
We have this package maintained in `end-to-end` and never backported.
```
git cherry-pick f02865c040a2b279bdd4a12c8dba12159009e90d e035bf06c5ccd65fe0c2b19bfacfb0d130db0858
```
> [backport] python3Packages.aws_secretsmanager_caching: init at 1.1.1.5

- pkgs/development/libraries/hyperscan/default.nix
- pkgs/development/python-modules/hyperscan/default.nix
- pkgs/development/python-modules/pdm-backend/default.nix
- pkgs/top-level/python-packages.nix
I had to vendor:
- `python3Packages.hyperscan`: `[nativeCheckInputs -> checkInputs](https://github.com/awakesecurity/nixpkgs/commit/179c42876f40b09282e1bdebcf5066aff59d5503), [use older overrideAttrs format](https://github.com/awakesecurity/nixpkgs/commit/5548c9f23dcd1bcac0e8442bf74d4b0a20b64af8)
- `hyperscan`: [checkPhase -> installCheckPhase](https://github.com/awakesecurity/nixpkgs/commit/09446d1e6347a562ac47b2757f27978ffd5cf91b). In `checkPhase` it failed: `bin/unit-hyperscan: error while loading shared libraries: libhs.so.5: cannot open shared object file: No such file or directory`, but in `installCheckPhase` and in final derivation this file exists. @jsoo1 have you seen something like that before? Are you ok with this change?
> [backport] python3Packages.hyperscan: init at 0.6.0

- pkgs/development/libraries/libressl/default.nix
- pkgs/top-level/aliases.nix
- pkgs/top-level/all-packages.nix
Fixes:
* CVE-2022-48437
* CVE-2023-35784
> libressl: 3.5.2 -> 3.7.3

- pkgs/development/libraries/fribidi/default.nix
Fixes:
* CVE-2022-25308
* CVE-2022-25309
* CVE-2022-25310
> fribidi: 1.0.10 -> 1.0.13

- pkgs/tools/networking/inetutils/default.nix
Fixes:
* CVE-2022-39028
* CVE-2023-40303
> inetutils: 2.2 -> 2.4

- nixos/maintainers/scripts/ec2/amazon-image.nix
The duplicate import of pkgs did not forward nixpkgs options.
> amazon-image: do not reimport pkgs

- nixos/modules/services/monitoring/grafana.nix
Grafana will unconditionally call chown on the socket after creating it, even if the configuration does not ask for a different socket gid.
> nixos/grafana: allow @chown syscalls when using unix sockets

- pkgs/build-support/fetchgit/nix-prefetch-git
This reverts commit 1dfaad73ed98254c1c0522156fe45b115e0a8eb4.
> Revert "nix-prefetch-git: Fix inconsistency with fetchgit regarding deepClone"

- nixos/modules/services/databases/clickhouse.nix
Change clickhouse's module conf directory to permit overrides
> Clickhouse: Allow merging config files in /etc

- nixos/modules/services/databases/clickhouse.nix
- pkgs/development/java-modules/clickhouse_jdbc/default.nix
- pkgs/development/java-modules/liquibase_clickhouse/default.nix
- pkgs/development/tools/database/liquibase/default.nix
- pkgs/top-level/all-packages.nix
Introduces clickhouse-jdbc, liquibase-clickhouse Java modules.
Uses liquibase-clickhouse local version to avoid use of obsolete clickhouse-jdbc
Make clickhouse users.xml configurable
Use `shaded` uberjar for liquibase-clickhouse to avoid managing transitive dependencies.
> Add clickhouse_jdbc, liquibase_clickhouse, and link to liquibase script

- nixos/modules/services/databases/clickhouse.nix
Fix usersXml optionality issue introduced in https://github.com/awakesecurity/nixpkgs/pull/201
> Redo clickhouse service usersXml optionality

- nixos/modules/module-list.nix
- nixos/modules/services/infrastructure/terraform-cloud-agent/default.nix
- pkgs/tools/infrastructure/terraform-cloud-agent/default.nix
- pkgs/top-level/all-packages.nix
Redo of #181. NB review comments from that PR are addressed on this branch (I linked the commits in each comment on the original PR).
This change adds a derivation for the [`terraform-cloud-agent`][1] executable and a NixOS module that defines a systemd service for running that agent.
[1]: https://developer.hashicorp.com/terraform/cloud-docs/agents.
> terraform-cloud-agent: initialize derivation & NixOS service module

- pkgs/applications/virtualization/docker/default.nix
to address [CVE-2024-21626](https://nvd.nist.gov/vuln/detail/CVE-2024-21626)
> docker-runc: 1.1.2 -> 1.1.12

- pkgs/development/java-modules/liquibase_clickhouse/default.nix
The existing liquibase-clickhouse was compatible with liquibase
4.17-4.22, but a recent upgrade to liquibase 4.23.0 broke things.
> Fix liquibase-clickhouse brokenness with tools/database/liquibase

- nixos/modules/system/boot/binfmt.nix
We shouldn't be creating a systemd.services.systemd-binfmt value when the upstream unit isn't being pulled in, because it results in a service unit file with no ExecStart line
> binfmt: Don't create invalid service with no registrations

- nixos/modules/services/monitoring/graphite.nix
`django-admin.py` is deprecated in django3, and removed in django4, so graphite must use `django-admin` instead
> graphiteWeb: use non-deprecated django-admin command

- nixos/modules/services/databases/postgresql.nix
There is a timeout of 2 minutes for start and stop of postgresql. However, upgrades can take much longer.
I've discovered that we can extend timeout using systemd-notify only during active upgrade instead of changing the limit globally.
See:
- https://www.freedesktop.org/software/systemd/man/latest/sd_notify.html#EXTEND_TIMEOUT_USEC=%E2%80%A6
- https://www.freedesktop.org/software/systemd/man/latest/systemd-notify.html
> nixos/postgresql: increase systemd timeout during upgrade

- nixos/modules/services/web-servers/nginx/default.nix
Backport of: https://github.com/NixOS/nixpkgs/pull/257828 (specifically: https://github.com/NixOS/nixpkgs/commit/ea1eb4ee0fa44dd4cd37e8ece2634370d1c2b0d2.patch).
> Backport nixos/nginx: add systemd-tmpfiles exclusion of temporary directories

- nixos/modules/services/misc/sssd.nix
Since the configuration assumes nscd.conf exists and nss is configured
> nixos/sssd: assert that nscd is enabled

- pkgs/development/python-modules/black/default.nix
- pkgs/development/python-modules/hatchling/default.nix
This is to upgrade it ahead of nixpkgs bump so the diff on the bump branch is managable.
These will be dropped during the next bump, since they are already applied there
> python3Packages.black: 23.11.0 -> 24.2.0 

- pkgs/tools/networking/openssh/common.nix
- pkgs/tools/networking/openssh/default.nix
Fixes CVE-2025-26465 and CVE-2025-26466.
https://www.qualys.com/2025/02/18/openssh-mitm-dos.txt
backport of: #246
with intermediate commits dropped
> [5.3][CVE-2025-26465][CVE-2025-26466] openssh: 9.8p1 -> 9.9p2

- nixos/modules/services/databases/postgresql.nix
This reverts commit e25632036e707f695d2d5473038f3d5cb3c00c57.
> Revert "drop! nixos/postgresql: fix `extraPlugins` type"

- pkgs/tools/package-management/lix/default.nix
This reverts commit 01c1efce1badef986e08694b72cb43b00a82e7ec.
While we track down and fix related issues.
> Revert "lixPackageSets.lix_2_92: patch for CVE-2025-4641{5,6}"

- pkgs/by-name/li/libavif/package.nix
Cherry pick the package bump for patching vulnerability on package version.
- Built on platform:
- Tested, as applicable:
- Nixpkgs Release Notes
- NixOS Release Notes
[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage
[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: …
> MONAPP-41664: CVE-2025-48174, CVE-2025-48175 Patch on Libavif [NIXPKGS-R5.4]
